# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Money',
        ),
    ]
